name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Docker Hub Images
        run: |
          IMAGE_NAMES=("multi-client" "multi-nginx" "multi-server" "multi-worker")
          for IMAGE in "${IMAGE_NAMES[@]}"; do
            curl -s -X DELETE \
              -H "Authorization: Bearer ${{ secrets.DOCKER_ACCESS_TOKEN }}" \
              "https://hub.docker.com/v2/repositories/josemartinez1987/$IMAGE/"
            echo "Deleted image: $IMAGE"
          done

      - uses: actions/checkout@v3

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Test React App
        run: |
          docker build -t josemartinez1987/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true josemartinez1987/react-test npm test

      - name: Build Docker Images
        run: |
          docker build -t josemartinez1987/multi-client ./client
          docker build -t josemartinez1987/multi-nginx ./nginx
          docker build -t josemartinez1987/multi-server ./server
          docker build -t josemartinez1987/multi-worker ./worker

      - name: Push Docker Images
        run: |
          docker push josemartinez1987/multi-client
          docker push josemartinez1987/multi-nginx
          docker push josemartinez1987/multi-server
          docker push josemartinez1987/multi-worker

      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-655786143075
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip